# Generated by Django 6.0.5 on 2026-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('topic', models.CharField(max_length=32)),
                ('difficulty', models.CharField(max_length=32)),
                ('prerequisites', models.ManyToManyField(blank=True, to='api.course')),
            ],
        ),
    ]
