# Generated by Django 6.0.5 on 2026-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topic_display_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
